# Generated by Django 4.2.6 on 2023-10-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('recipient', models.CharField(max_length=255)),
                ('delivery_date', models.DateField()),
                ('occasion', models.CharField(max_length=255)),
                ('packaging_condition', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('personal_note', models.TextField()),
                ('delivery_status', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('depth', models.FloatField()),
                ('surprise_level', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
            ],
        ),
    ]
