# Generated by Django 4.2.6 on 2023-10-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cadeau',
            new_name='Product',
        ),
    ]
